const MEDIA_ORIGIN = 'https://launchpad-media.jerryquinet.workers.dev';
const media = (slug, kind, filename) => `${MEDIA_ORIGIN}/media/${encodeURIComponent(slug)}/${kind}/${filename}`;

// A deliberately small deterministic fixture for localhost and CI. Production
// always hydrates the complete canonical catalog from the public R2 Worker.
export const catalogFixture = [
  {
    id: 'before-the-noise',
    title: 'Before the Noise',
    file: media('before-the-noise', 'audio', 'audio.mp3'),
    cover: media('before-the-noise', 'thumbnail', 'thumbnail.webp'),
    fullCover: media('before-the-noise', 'cover', 'cover.jpeg'),
    genre: 'Hip-hop',
    tags: ['Hip-hop', 'Boom Bap', 'Lo-fi'],
    mood: 'Digital melancholy',
    albumId: 'neon-heartbreaks',
    album: 'Neon Heartbreaks',
    lyrics: media('before-the-noise', 'lyrics', 'lyrics.txt'),
    accent: '#ef9542',
    accent2: '#7f8c83',
    languages: ['English'],
    bpm: 152,
    key: 'D# minor',
    keyConfidence: 0.336,
    explicit: false,
    duration: 237,
    remote: true,
    source: 'local-test-fixture'
  },
  {
    id: 'thick',
    title: 'THICK',
    file: media('thick', 'audio', 'audio.mp3'),
    cover: media('thick', 'thumbnail', 'thumbnail.webp'),
    fullCover: media('thick', 'cover', 'cover.jpeg'),
    video: media('thick', 'video', 'video.mp4'),
    videoContentType: 'video/mp4',
    videoFilename: 'video.mp4',
    genre: 'Hip-hop',
    tags: ['Hip-hop', 'Confidence'],
    mood: 'Heavy confidence',
    albumId: 'coal-to-diamond',
    album: 'Coal to Diamond',
    lyrics: media('thick', 'lyrics', 'lyrics.txt'),
    accent: '#ff3f5f',
    accent2: '#7d34ff',
    languages: ['English'],
    bpm: 136,
    key: 'G minor',
    keyConfidence: 1,
    explicit: false,
    duration: 231.6,
    remote: true,
    source: 'local-test-fixture'
  },
  {
    id: 'saigon-bound',
    title: 'Saigon Bound',
    file: media('saigon-bound', 'audio', 'audio.mp3'),
    cover: media('saigon-bound', 'thumbnail', 'thumbnail.webp'),
    fullCover: media('saigon-bound', 'cover', 'cover.png'),
    genre: 'Vietnam',
    tags: ['Vietnam', 'Hip-hop'],
    mood: 'Travel story',
    albumId: 'love-letters-from-saigon',
    album: 'Love Letters from Saigon',
    lyrics: media('saigon-bound', 'lyrics', 'lyrics.txt'),
    accent: '#ff8a3d',
    accent2: '#d93cff',
    languages: ['English'],
    bpm: 136,
    key: 'G# major',
    keyConfidence: 0.439,
    explicit: false,
    duration: 209.76,
    remote: true,
    source: 'local-test-fixture'
  },
  {
    id: 'ghost-signal',
    title: 'Ghost Signal',
    file: media('ghost-signal', 'audio', 'audio.mp3'),
    cover: media('ghost-signal', 'thumbnail', 'thumbnail.webp'),
    fullCover: media('ghost-signal', 'cover', 'cover.jpeg'),
    genre: 'R&B',
    tags: ['R&B', 'Love'],
    mood: 'Future R&B, Synthwave, Electronic Pop',
    albumId: 'singles',
    album: 'Singles',
    lyrics: null,
    accent: '#41d6ff',
    accent2: '#8a52ff',
    languages: ['English'],
    bpm: 129,
    key: 'G# minor',
    keyConfidence: 0.725,
    explicit: null,
    duration: 205.2,
    remote: true,
    source: 'local-test-fixture'
  }
];
